from deepmedic.gui.ui_config_create import *
from PySide2 import QtCore, QtGui, QtWidgets


class UiPreprocConfig(UiConfig):
    def setup_ui(self, model_config_create, Config, window_type=''):
        model_config_create.setObjectName("model_config_create")
        model_config_create.resize(600, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(model_config_create.sizePolicy().hasHeightForWidth())
        model_config_create.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(model_config_create)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.centralLayout.setSpacing(0)
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.centralLayout.setObjectName("centralLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -785, 584, 1179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        widget_num = 0
        for section in Config.config_data.get_sorted_sections():
            if not section.advanced:
                widget_num = self.add_title(section.name, section.text, widget_num)
                for elem in section.get_sorted_elems():
                    if not elem.advanced:
                        widget_num = self.add_grid_row(section.name + '_' + elem.name, widget_num, elem)
                if section.name == 'data':
                    self.data_checks_progress = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
                    self.data_checks_progress.setObjectName("data_checks_progress")
                    self.gridLayout.addWidget(self.data_checks_progress, widget_num, LABEL_COL, 1, SAVE_BUTTON_SIZE)
                    self.data_checks_text = QtWidgets.QLabel(self.scrollAreaWidgetContents)
                    self.data_checks_text.setObjectName("data_checks_text")
                    self.gridLayout.addWidget(self.data_checks_text, widget_num + 1, LABEL_COL, 1, SAVE_BUTTON_SIZE)
                    self.data_checks_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
                    self.data_checks_button.setObjectName("data_checks_button")
                    self.data_checks_button.setText('Run Data Checks')
                    self.gridLayout.addWidget(self.data_checks_button, widget_num + 2, LABEL_COL, 1, SAVE_BUTTON_SIZE)
                    widget_num += 3

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, widget_num, 0, 1, 3)
        self.preprocess_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.preprocess_button.setObjectName("preprocess_button")
        self.preprocess_button.setText('Preprocess Data')
        self.gridLayout.addWidget(self.preprocess_button, widget_num + 1, LABEL_COL, 1, SAVE_BUTTON_SIZE)
        self.save_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.save_button.setObjectName("save_button")
        self.save_button.setText('Save Configuration File')
        self.gridLayout.addWidget(self.save_button, widget_num + 2, LABEL_COL, 1, SAVE_BUTTON_SIZE)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.centralLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        model_config_create.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(model_config_create)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        model_config_create.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(model_config_create)
        self.statusbar.setObjectName("statusbar")
        model_config_create.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(model_config_create)
        self.action_open.setObjectName("action_open")
        self.action_save_as = QtWidgets.QAction(model_config_create)
        self.action_save_as.setObjectName("action_save_as")
        self.action_clear_all = QtWidgets.QAction(model_config_create)
        self.action_clear_all.setObjectName("action_clear_all")
        self.action_close = QtWidgets.QAction(model_config_create)
        self.action_close.setObjectName("action_close")
        self.action_save = QtWidgets.QAction(model_config_create)
        self.action_save.setObjectName("action_save")
        self.action_load = QtWidgets.QAction(model_config_create)
        self.action_load.setObjectName("action_load")
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_load)
        self.menuFile.addAction(self.action_save)
        self.menuFile.addAction(self.action_save_as)
        self.menuFile.addAction(self.action_close)
        self.menuEdit.addAction(self.action_clear_all)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslate_ui(model_config_create, window_type)
        QtCore.QMetaObject.connectSlotsByName(model_config_create)